apiVersion: apps/v1
kind: Deployment
metadata:
  name: kasplo-deployment
  labels:
    app: webapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp 
    spec:
      containers:
      - name: webserver
        image: kasplo-api:latest
        ports:
        - containerPort: 80